# This file specifies a GitHub action that copies this repository into the
# private repository DivinePine/braers-copy-repo on every push to the main branch.
# This is done in order to be able to use the repo on vercel, which does not allow
# usage of organisation repositories on their free price plan.
name: (main) push to external repo
on:
  push:
    branches:
      - main
jobs:
  push-to-external-repo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: push to external repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SSH_DEPLOY_KEY }}
          publish_dir: .
          external_repository: DivinePine/braers-copy-repo
          publish_branch: main
          allow_empty_commit: true